import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        // ── Organic Light Theme (M3 Earthy/Olive) ─────────────────────────────
        "on-tertiary-container":       "#f6e6c3",
        "surface-container-highest":   "#e2e2e2",
        "primary-fixed-dim":           "#b9cf80",
        "surface-container-low":       "#f4f3f3",
        "primary-fixed":               "#d5ec99",
        "on-tertiary":                 "#ffffff",
        "tertiary":                    "#594f34",
        "on-primary-fixed-variant":    "#3b4d0b",
        "on-primary-fixed":            "#151f00",
        "surface-container-high":      "#e8e8e8",
        "error":                       "#ba1a1a",
        "on-secondary-container":      "#6a3500",
        "tertiary-fixed-dim":          "#d4c5a3",
        "inverse-primary":             "#b9cf80",
        "secondary-container":         "#fc9842",
        "inverse-on-surface":          "#f1f1f1",
        "on-secondary":                "#ffffff",
        "on-secondary-fixed":          "#2f1400",
        "surface-dim":                 "#dadada",
        "inverse-surface":             "#2f3131",
        "on-error-container":          "#93000a",
        "error-container":             "#ffdad6",
        "secondary-fixed":             "#ffdcc4",
        "outline":                     "#76786a",
        "secondary":                   "#924c00",
        "on-tertiary-fixed-variant":   "#50462c",
        "on-primary":                  "#ffffff",
        "surface-container-lowest":    "#ffffff",
        "on-secondary-fixed-variant":  "#6f3800",
        "surface-bright":              "#f9f9f9",
        "on-surface":                  "#1a1c1c",
        "secondary-fixed-dim":         "#ffb780",
        "background":                  "#f9f9f9",
        "on-background":               "#1a1c1c",
        "outline-variant":             "#c6c8b7",
        "tertiary-fixed":              "#f1e1be",
        "tertiary-container":          "#72674b",
        "on-error":                    "#ffffff",
        "on-surface-variant":          "#45483b",
        "surface":                     "#f9f9f9",
        "primary-container":           "#5c6f2b",
        "surface-variant":             "#e2e2e2",
        "surface-container":           "#eeeeee",
        "on-tertiary-fixed":           "#221b05",
        "on-primary-container":        "#daf19e",
        "primary":                     "#445614",
        "surface-tint":                "#536522",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        "3xl":   "1.5rem",
        full:    "9999px",
      },
      fontFamily: {
        sans:     ["Public Sans", "sans-serif"],
        "public": ["Public Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg":   ["48px", { lineHeight: "56px",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg":  ["32px", { lineHeight: "40px",  letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md":  ["24px", { lineHeight: "32px",  fontWeight: "600" }],
        "body-lg":      ["18px", { lineHeight: "28px",  fontWeight: "400" }],
        "body-md":      ["16px", { lineHeight: "24px",  fontWeight: "400" }],
        "body-sm":      ["14px", { lineHeight: "20px",  fontWeight: "400" }],
        "label-md":     ["12px", { lineHeight: "16px",  letterSpacing: "0.05em", fontWeight: "600" }],
      },
      spacing: {
        base:   "8px",
        xs:     "4px",
        sm:     "12px",
        md:     "24px",
        lg:     "48px",
        xl:     "80px",
        gutter: "24px",
        margin: "32px",
      },
      keyframes: {
        shimmer:    { "0%": { transform: "translateX(-100%)" }, "100%": { transform: "translateX(100%)" } },
        "fade-in":  { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "slide-up": { from: { opacity: "0", transform: "translateY(12px)" }, to: { opacity: "1", transform: "translateY(0)" } },
      },
      animation: {
        shimmer:    "shimmer 2s infinite",
        "fade-in":  "fade-in 0.3s ease-out",
        "slide-up": "slide-up 0.25s ease-out",
      },
    },
  },
  plugins: [],
};
export default config;
